In [3]:
from d3rlpy.dataset import MDPDataset
import d3rlpy
import numpy as np
import pandas as pd
import tqdm

/Users/yifeili/miniforge3/envs/llm-rl/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
dataset_name = 'OVERRULING'
traj_type = 'CR'
file = f'../data/{dataset_name}/{dataset_name}_rl_dataset_train_{traj_type}.h5'
with open(file, "rb") as f:
    dataset = d3rlpy.dataset.ReplayBuffer.load(f, d3rlpy.dataset.InfiniteBuffer())
cql = d3rlpy.algos.DiscreteCQLConfig(batch_size=128).create(device="cpu")
cql.fit(
    dataset,
    n_steps=steps_per_epoch*epochs[traj_type],
    n_steps_per_epoch=steps_per_epoch,
    experiment_name=f'cql_{dataset_name}_{traj_type}',

)

In [32]:
datasets = ['OVERRULING', 'HEADLINES', 'SCIQ']
traj_types = ['C', 'CR', 'CRG']
steps_per_epoch = 10000
epochs = {'C':2, 'CR':5, 'CRG':8}
for dataset_name in datasets:
    for traj_type in traj_types:
        file = f'../data/{dataset_name}/{dataset_name}_rl_dataset_train_{traj_type}.h5'
        with open(file, "rb") as f:
            dataset = d3rlpy.dataset.ReplayBuffer.load(f, d3rlpy.dataset.InfiniteBuffer())
        cql = d3rlpy.algos.DiscreteCQLConfig(batch_size=128).create(device="cpu")
        cql.fit(
            dataset,
            n_steps=steps_per_epoch*epochs[traj_type],
            n_steps_per_epoch=steps_per_epoch,
            experiment_name=f'cql_{dataset_name}_{traj_type}',
        
        )

2025-04-12 16:18.57 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:18.57 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:18.57 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:18.57 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:18.57 [debug    ] Building models...            
2025-04-12 16:18.57 [debug    ] Models have been built.       
2025-04-12 16:18.57 [in

Epoch 1/2: 100%|██████████| 10000/10000 [00:36<00:00, 272.96it/s, loss=0.0954, td_loss=0.0158, conservative_loss=0.0797]

2025-04-12 16:19.34 [info     ] cql_OVERRULING_C_20250412161857: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0012421300411224365, 'time_algorithm_update': 0.002310891318321228, 'loss': 0.0953656980292406, 'td_loss': 0.01576805836770218, 'conservative_loss': 0.07959763964134327, 'time_step': 0.0036458707094192506} step=10000
2025-04-12 16:19.34 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_C_20250412161857/model_10000.d3



Epoch 2/2: 100%|██████████| 10000/10000 [00:38<00:00, 262.99it/s, loss=0.00319, td_loss=0.00307, conservative_loss=0.000111]

2025-04-12 16:20.12 [info     ] cql_OVERRULING_C_20250412161857: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0013127118110656739, 'time_algorithm_update': 0.002372898602485657, 'loss': 0.0031842807803303, 'td_loss': 0.00307379110698821, 'conservative_loss': 0.00011048967450442432, 'time_step': 0.0037836700916290284} step=20000
2025-04-12 16:20.12 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_C_20250412161857/model_20000.d3


2025-04-12 16:20.13 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:20.13 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:20.13 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:20.13 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:20.13 [debug    ] Building models...            
2025-04-12 16:20.13 [debug    ] Models have been built.       
2025-04-12 16:20.13 [in

Epoch 1/5: 100%|██████████| 10000/10000 [00:38<00:00, 261.13it/s, loss=2.6, td_loss=0.253, conservative_loss=2.35]

2025-04-12 16:20.51 [info     ] cql_OVERRULING_CR_20250412162013: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0013275422573089599, 'time_algorithm_update': 0.0023798925876617433, 'loss': 2.60012008626461, 'td_loss': 0.2530414301097393, 'conservative_loss': 2.3470786562681196, 'time_step': 0.0038098979473114012} step=10000
2025-04-12 16:20.51 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CR_20250412162013/model_10000.d3



Epoch 2/5: 100%|██████████| 10000/10000 [00:38<00:00, 260.49it/s, loss=2.34, td_loss=0.246, conservative_loss=2.09]

2025-04-12 16:21.29 [info     ] cql_OVERRULING_CR_20250412162013: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0013360891580581665, 'time_algorithm_update': 0.0023810309648513795, 'loss': 2.3362030951023103, 'td_loss': 0.24640449902042746, 'conservative_loss': 2.0897985954761507, 'time_step': 0.003819140625} step=20000


2025-04-12 16:21.29 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CR_20250412162013/model_20000.d3


Epoch 3/5: 100%|██████████| 10000/10000 [00:39<00:00, 253.70it/s, loss=2.01, td_loss=0.226, conservative_loss=1.78]

2025-04-12 16:22.09 [info     ] cql_OVERRULING_CR_20250412162013: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.0013786875247955323, 'time_algorithm_update': 0.0024372009992599487, 'loss': 2.0099037349939346, 'td_loss': 0.22608231897801162, 'conservative_loss': 1.7838214163780213, 'time_step': 0.003921353888511657} step=30000
2025-04-12 16:22.09 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CR_20250412162013/model_30000.d3



Epoch 4/5: 100%|██████████| 10000/10000 [00:42<00:00, 232.77it/s, loss=1.7, td_loss=0.207, conservative_loss=1.49]

2025-04-12 16:22.52 [info     ] cql_OVERRULING_CR_20250412162013: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.001502958083152771, 'time_algorithm_update': 0.0026570781707763672, 'loss': 1.6958591953516007, 'td_loss': 0.2068948924459517, 'conservative_loss': 1.488964302968979, 'time_step': 0.004272503733634948} step=40000
2025-04-12 16:22.52 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CR_20250412162013/model_40000.d3



Epoch 5/5: 100%|██████████| 10000/10000 [00:42<00:00, 233.61it/s, loss=1.43, td_loss=0.191, conservative_loss=1.24]

2025-04-12 16:23.35 [info     ] cql_OVERRULING_CR_20250412162013: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0014991941452026367, 'time_algorithm_update': 0.0026440659761428832, 'loss': 1.428537598657608, 'td_loss': 0.19089137673825027, 'conservative_loss': 1.2376462213754653, 'time_step': 0.004256860136985779} step=50000
2025-04-12 16:23.35 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CR_20250412162013/model_50000.d3


2025-04-12 16:23.36 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:23.36 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:23.36 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:23.36 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:23.36 [debug    ] Building models...            
2025-04-12 16:23.36 [debug    ] Models have been built.       
2025-04-12 16:23.36 [in

Epoch 1/8: 100%|██████████| 10000/10000 [00:41<00:00, 239.17it/s, loss=2.92, td_loss=0.401, conservative_loss=2.51]

2025-04-12 16:24.18 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0014521595001220702, 'time_algorithm_update': 0.0025965834856033327, 'loss': 2.915334658718109, 'td_loss': 0.4012471608698368, 'conservative_loss': 2.514087497019768, 'time_step': 0.004158743810653687} step=10000
2025-04-12 16:24.18 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_10000.d3



Epoch 2/8: 100%|██████████| 10000/10000 [00:41<00:00, 239.32it/s, loss=2.8, td_loss=0.384, conservative_loss=2.41]

2025-04-12 16:24.59 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0014663384199142457, 'time_algorithm_update': 0.0025776437997817995, 'loss': 2.798303907799721, 'td_loss': 0.3835509374991059, 'conservative_loss': 2.414752969813347, 'time_step': 0.004155101704597473} step=20000
2025-04-12 16:24.59 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_20000.d3



Epoch 3/8: 100%|██████████| 10000/10000 [00:41<00:00, 239.65it/s, loss=2.62, td_loss=0.366, conservative_loss=2.25]

2025-04-12 16:25.41 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.0014558623313903809, 'time_algorithm_update': 0.0025829246044158935, 'loss': 2.619636965298653, 'td_loss': 0.36623602263927457, 'conservative_loss': 2.2534009432196616, 'time_step': 0.004150036287307739} step=30000
2025-04-12 16:25.41 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_30000.d3



Epoch 4/8: 100%|██████████| 10000/10000 [00:41<00:00, 239.68it/s, loss=2.43, td_loss=0.353, conservative_loss=2.07]

2025-04-12 16:26.23 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.0014540610551834106, 'time_algorithm_update': 0.0025833067178726195, 'loss': 2.426536476969719, 'td_loss': 0.353401636312902, 'conservative_loss': 2.0731348403692245, 'time_step': 0.004149993586540222} step=40000
2025-04-12 16:26.23 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_40000.d3



Epoch 5/8: 100%|██████████| 10000/10000 [00:41<00:00, 241.62it/s, loss=2.23, td_loss=0.333, conservative_loss=1.89]

2025-04-12 16:27.04 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0014459784507751465, 'time_algorithm_update': 0.0025595883131027224, 'loss': 2.2262792244315146, 'td_loss': 0.33319629940092566, 'conservative_loss': 1.893082925415039, 'time_step': 0.004115361404418945} step=50000
2025-04-12 16:27.04 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_50000.d3



Epoch 6/8: 100%|██████████| 10000/10000 [00:42<00:00, 237.68it/s, loss=2.05, td_loss=0.324, conservative_loss=1.73]

2025-04-12 16:27.46 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=6 step=60000 epoch=6 metrics={'time_sample_batch': 0.0014551867485046387, 'time_algorithm_update': 0.002617447304725647, 'loss': 2.051160517811775, 'td_loss': 0.32387969417274, 'conservative_loss': 1.727280823457241, 'time_step': 0.004184613704681397} step=60000
2025-04-12 16:27.46 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_60000.d3



Epoch 7/8: 100%|██████████| 10000/10000 [00:44<00:00, 225.55it/s, loss=1.91, td_loss=0.319, conservative_loss=1.59]

2025-04-12 16:28.31 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=7 step=70000 epoch=7 metrics={'time_sample_batch': 0.0014959459066390991, 'time_algorithm_update': 0.0027996283769607545, 'loss': 1.9054246172904967, 'td_loss': 0.3191152616843581, 'conservative_loss': 1.586309355056286, 'time_step': 0.004409888529777527} step=70000
2025-04-12 16:28.31 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_70000.d3



Epoch 8/8: 100%|██████████| 10000/10000 [00:44<00:00, 223.50it/s, loss=1.77, td_loss=0.307, conservative_loss=1.46]

2025-04-12 16:29.15 [info     ] cql_OVERRULING_CRG_20250412162336: epoch=8 step=80000 epoch=8 metrics={'time_sample_batch': 0.0015051955699920655, 'time_algorithm_update': 0.0028311538457870484, 'loss': 1.769640502345562, 'td_loss': 0.30720923735499384, 'conservative_loss': 1.4624312646508217, 'time_step': 0.004450273036956787} step=80000
2025-04-12 16:29.15 [info     ] Model parameters are saved to d3rlpy_logs/cql_OVERRULING_CRG_20250412162336/model_80000.d3


2025-04-12 16:29.17 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:29.17 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:29.17 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:29.17 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:29.17 [debug    ] Building models...            
2025-04-12 16:29.17 [debug    ] Models have been built.       
2025-04-12 16:29.17 [in

Epoch 1/2: 100%|██████████| 10000/10000 [00:43<00:00, 230.00it/s, loss=0.126, td_loss=0.0304, conservative_loss=0.0954]

2025-04-12 16:30.01 [info     ] cql_HEADLINES_C_20250412162917: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.001529047727584839, 'time_algorithm_update': 0.0026844671487808226, 'loss': 0.12566821581502444, 'td_loss': 0.03037454865523614, 'conservative_loss': 0.09529366716187214, 'time_step': 0.00432382652759552} step=10000
2025-04-12 16:30.01 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_C_20250412162917/model_10000.d3



Epoch 2/2: 100%|██████████| 10000/10000 [00:44<00:00, 224.29it/s, loss=0.0238, td_loss=0.0226, conservative_loss=0.0012]

2025-04-12 16:30.45 [info     ] cql_HEADLINES_C_20250412162917: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.001550373101234436, 'time_algorithm_update': 0.002767643737792969, 'loss': 0.023788515663798897, 'td_loss': 0.022591098784469067, 'conservative_loss': 0.0011974168852728327, 'time_step': 0.004433637976646423} step=20000
2025-04-12 16:30.45 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_C_20250412162917/model_20000.d3


2025-04-12 16:30.49 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:30.49 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:30.49 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:30.49 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:30.49 [debug    ] Building models...            
2025-04-12 16:30.49 [debug    ] Models have been built.       
2025-04-12 16:30.49 [in

Epoch 1/5: 100%|██████████| 10000/10000 [00:47<00:00, 210.38it/s, loss=2.55, td_loss=0.131, conservative_loss=2.42]

2025-04-12 16:31.36 [info     ] cql_HEADLINES_CR_20250412163049: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0016127065658569336, 'time_algorithm_update': 0.002994201421737671, 'loss': 2.548443878912926, 'td_loss': 0.13109132361747325, 'conservative_loss': 2.4173525548696517, 'time_step': 0.004725676703453064} step=10000
2025-04-12 16:31.36 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CR_20250412163049/model_10000.d3



Epoch 2/5: 100%|██████████| 10000/10000 [00:46<00:00, 214.00it/s, loss=2.54, td_loss=0.128, conservative_loss=2.41]

2025-04-12 16:32.23 [info     ] cql_HEADLINES_CR_20250412163049: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0015962193489074707, 'time_algorithm_update': 0.002931850862503052, 'loss': 2.5389686798334123, 'td_loss': 0.12807012914456428, 'conservative_loss': 2.410898550415039, 'time_step': 0.004646619653701782} step=20000
2025-04-12 16:32.23 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CR_20250412163049/model_20000.d3



Epoch 3/5: 100%|██████████| 10000/10000 [00:46<00:00, 216.46it/s, loss=2.53, td_loss=0.14, conservative_loss=2.39]

2025-04-12 16:33.09 [info     ] cql_HEADLINES_CR_20250412163049: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.001580411720275879, 'time_algorithm_update': 0.0028950948476791382, 'loss': 2.5275174853563307, 'td_loss': 0.1403271088782698, 'conservative_loss': 2.3871903765678404, 'time_step': 0.004593542265892029} step=30000
2025-04-12 16:33.09 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CR_20250412163049/model_30000.d3



Epoch 4/5: 100%|██████████| 10000/10000 [00:45<00:00, 217.63it/s, loss=2.5, td_loss=0.153, conservative_loss=2.35]

2025-04-12 16:33.55 [info     ] cql_HEADLINES_CR_20250412163049: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.0015788017988204955, 'time_algorithm_update': 0.002870442056655884, 'loss': 2.501502407002449, 'td_loss': 0.15351110915578903, 'conservative_loss': 2.347991298508644, 'time_step': 0.004569013118743897} step=40000
2025-04-12 16:33.55 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CR_20250412163049/model_40000.d3



Epoch 5/5: 100%|██████████| 10000/10000 [00:45<00:00, 217.40it/s, loss=2.47, td_loss=0.167, conservative_loss=2.3]

2025-04-12 16:34.41 [info     ] cql_HEADLINES_CR_20250412163049: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0015817300081253053, 'time_algorithm_update': 0.002874180006980896, 'loss': 2.4651189342975615, 'td_loss': 0.16675160893946886, 'conservative_loss': 2.298367326140404, 'time_step': 0.0045740100383758545} step=50000
2025-04-12 16:34.41 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CR_20250412163049/model_50000.d3


2025-04-12 16:34.46 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:34.46 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:34.46 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:34.47 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:34.47 [debug    ] Building models...            
2025-04-12 16:34.47 [debug    ] Models have been built.       
2025-04-12 16:34.47 [in

Epoch 1/8: 100%|██████████| 10000/10000 [00:44<00:00, 223.95it/s, loss=2.67, td_loss=0.167, conservative_loss=2.5]

2025-04-12 16:35.31 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.001540803289413452, 'time_algorithm_update': 0.002784018540382385, 'loss': 2.6713885205984114, 'td_loss': 0.1674833866238594, 'conservative_loss': 2.50390513381958, 'time_step': 0.004439755320549011} step=10000
2025-04-12 16:35.31 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_10000.d3



Epoch 2/8: 100%|██████████| 10000/10000 [00:45<00:00, 220.02it/s, loss=2.67, td_loss=0.167, conservative_loss=2.5]

2025-04-12 16:36.17 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0015625357627868652, 'time_algorithm_update': 0.002834231662750244, 'loss': 2.665862521100044, 'td_loss': 0.16666774557977915, 'conservative_loss': 2.499194775247574, 'time_step': 0.004519301533699035} step=20000
2025-04-12 16:36.17 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_20000.d3



Epoch 3/8: 100%|██████████| 10000/10000 [00:45<00:00, 218.67it/s, loss=2.65, td_loss=0.17, conservative_loss=2.48]

2025-04-12 16:37.02 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.0015750421524047852, 'time_algorithm_update': 0.002852701020240784, 'loss': 2.6543738957881926, 'td_loss': 0.1695757462196052, 'conservative_loss': 2.4847981487751007, 'time_step': 0.00454687557220459} step=30000
2025-04-12 16:37.02 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_30000.d3



Epoch 4/8: 100%|██████████| 10000/10000 [00:45<00:00, 218.90it/s, loss=2.64, td_loss=0.174, conservative_loss=2.46]

2025-04-12 16:37.48 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.0015745355367660523, 'time_algorithm_update': 0.0028482988834381104, 'loss': 2.6351294857501983, 'td_loss': 0.1737060001909733, 'conservative_loss': 2.4614234861135484, 'time_step': 0.004541616654396057} step=40000
2025-04-12 16:37.48 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_40000.d3



Epoch 5/8: 100%|██████████| 10000/10000 [00:45<00:00, 219.39it/s, loss=2.61, td_loss=0.178, conservative_loss=2.43]

2025-04-12 16:38.34 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0015810150384902954, 'time_algorithm_update': 0.0028326288938522338, 'loss': 2.6067864300489427, 'td_loss': 0.17819166811555623, 'conservative_loss': 2.4285947620630264, 'time_step': 0.004532097887992859} step=50000
2025-04-12 16:38.34 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_50000.d3



Epoch 6/8: 100%|██████████| 10000/10000 [00:44<00:00, 223.99it/s, loss=2.58, td_loss=0.182, conservative_loss=2.39]

2025-04-12 16:39.18 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=6 step=60000 epoch=6 metrics={'time_sample_batch': 0.0015471830606460571, 'time_algorithm_update': 0.0027740264654159547, 'loss': 2.575948015642166, 'td_loss': 0.18246961159333586, 'conservative_loss': 2.3934784041643145, 'time_step': 0.004439349603652954} step=60000
2025-04-12 16:39.18 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_60000.d3



Epoch 7/8: 100%|██████████| 10000/10000 [00:44<00:00, 223.02it/s, loss=2.55, td_loss=0.187, conservative_loss=2.36]

2025-04-12 16:40.03 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=7 step=70000 epoch=7 metrics={'time_sample_batch': 0.0015473392963409425, 'time_algorithm_update': 0.002794209146499634, 'loss': 2.5454192806959153, 'td_loss': 0.18750283033326268, 'conservative_loss': 2.357916448831558, 'time_step': 0.004458830809593201} step=70000
2025-04-12 16:40.03 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_70000.d3



Epoch 8/8: 100%|██████████| 10000/10000 [00:42<00:00, 234.48it/s, loss=2.51, td_loss=0.191, conservative_loss=2.32]

2025-04-12 16:40.46 [info     ] cql_HEADLINES_CRG_20250412163447: epoch=8 step=80000 epoch=8 metrics={'time_sample_batch': 0.0014930010557174683, 'time_algorithm_update': 0.0026368202209472655, 'loss': 2.5132410815238955, 'td_loss': 0.19124787073507904, 'conservative_loss': 2.3219932099342344, 'time_step': 0.004241946148872375} step=80000
2025-04-12 16:40.46 [info     ] Model parameters are saved to d3rlpy_logs/cql_HEADLINES_CRG_20250412163447/model_80000.d3


2025-04-12 16:40.48 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:40.48 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:40.48 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:40.48 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:40.48 [debug    ] Building models...            
2025-04-12 16:40.48 [debug    ] Models have been built.       
2025-04-12 16:40.48 [in

Epoch 1/2: 100%|██████████| 10000/10000 [00:43<00:00, 230.68it/s, loss=0.127, td_loss=0.028, conservative_loss=0.099] 

2025-04-12 16:41.31 [info     ] cql_SCIQ_C_20250412164048: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.001553087615966797, 'time_algorithm_update': 0.002648363995552063, 'loss': 0.12694599706362933, 'td_loss': 0.028019886871316704, 'conservative_loss': 0.09892611009227112, 'time_step': 0.004311831378936768} step=10000
2025-04-12 16:41.31 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_C_20250412164048/model_10000.d3



Epoch 2/2: 100%|██████████| 10000/10000 [00:46<00:00, 216.60it/s, loss=0.0279, td_loss=0.0103, conservative_loss=0.0176]


2025-04-12 16:42.18 [info     ] cql_SCIQ_C_20250412164048: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0016221529960632325, 'time_algorithm_update': 0.002853246021270752, 'loss': 0.027888122069020756, 'td_loss': 0.010312115718022687, 'conservative_loss': 0.017576006339583547, 'time_step': 0.004591421508789062} step=20000
2025-04-12 16:42.18 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_C_20250412164048/model_20000.d3
2025-04-12 16:42.22 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:42.22 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:42.22 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:42.22 [info     ] dataset info     

Epoch 1/5: 100%|██████████| 10000/10000 [00:50<00:00, 199.81it/s, loss=3.18, td_loss=0.755, conservative_loss=2.42]

2025-04-12 16:43.12 [info     ] cql_SCIQ_CR_20250412164222: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.001675788140296936, 'time_algorithm_update': 0.003176846385002136, 'loss': 3.1770649282455445, 'td_loss': 0.75513060144037, 'conservative_loss': 2.421934326696396, 'time_step': 0.0049751993656158445} step=10000


2025-04-12 16:43.12 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CR_20250412164222/model_10000.d3


Epoch 2/5: 100%|██████████| 10000/10000 [00:49<00:00, 202.32it/s, loss=3.17, td_loss=0.751, conservative_loss=2.42]

2025-04-12 16:44.01 [info     ] cql_SCIQ_CR_20250412164222: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0016581024169921876, 'time_algorithm_update': 0.0031325432062149047, 'loss': 3.168016837120056, 'td_loss': 0.7506959461450576, 'conservative_loss': 2.417320891237259, 'time_step': 0.004913788151741028} step=20000
2025-04-12 16:44.01 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CR_20250412164222/model_20000.d3



Epoch 3/5: 100%|██████████| 10000/10000 [00:49<00:00, 203.12it/s, loss=3.15, td_loss=0.753, conservative_loss=2.4]

2025-04-12 16:44.51 [info     ] cql_SCIQ_CR_20250412164222: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.0016502756595611573, 'time_algorithm_update': 0.003122321915626526, 'loss': 3.1494710211277006, 'td_loss': 0.7526012382939458, 'conservative_loss': 2.3968697828292846, 'time_step': 0.004895023512840271} step=30000
2025-04-12 16:44.51 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CR_20250412164222/model_30000.d3



Epoch 4/5: 100%|██████████| 10000/10000 [00:48<00:00, 206.23it/s, loss=3.11, td_loss=0.748, conservative_loss=2.36]

2025-04-12 16:45.39 [info     ] cql_SCIQ_CR_20250412164222: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.0016239697217941284, 'time_algorithm_update': 0.0030762784957885743, 'loss': 3.1069070564746855, 'td_loss': 0.7484216713428498, 'conservative_loss': 2.3584853856325148, 'time_step': 0.004821104669570923} step=40000


2025-04-12 16:45.39 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CR_20250412164222/model_40000.d3


Epoch 5/5: 100%|██████████| 10000/10000 [00:49<00:00, 201.84it/s, loss=3.05, td_loss=0.739, conservative_loss=2.31]

2025-04-12 16:46.29 [info     ] cql_SCIQ_CR_20250412164222: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0016842058181762696, 'time_algorithm_update': 0.0031152533054351807, 'loss': 3.0453359769821167, 'td_loss': 0.7392201245129109, 'conservative_loss': 2.306115851831436, 'time_step': 0.004925587940216064} step=50000
2025-04-12 16:46.29 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CR_20250412164222/model_50000.d3


2025-04-12 16:46.36 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2025-04-12 16:46.36 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.DISCRETE: 2>
2025-04-12 16:46.36 [info     ] Action size has been automatically determined. action_size=13
2025-04-12 16:46.36 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(603,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:46.36 [debug    ] Building models...            
2025-04-12 16:46.36 [debug    ] Models have been built.       
2025-04-12 16:46.36 [in

Epoch 1/8: 100%|██████████| 10000/10000 [00:43<00:00, 229.24it/s, loss=3.32, td_loss=0.78, conservative_loss=2.54]

2025-04-12 16:47.20 [info     ] cql_SCIQ_CRG_20250412164636: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0015590530395507812, 'time_algorithm_update': 0.0026646669149398804, 'loss': 3.3236124643564224, 'td_loss': 0.779879776057601, 'conservative_loss': 2.5437326886892317, 'time_step': 0.004337916445732117} step=10000
2025-04-12 16:47.20 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_10000.d3



Epoch 2/8: 100%|██████████| 10000/10000 [00:44<00:00, 222.91it/s, loss=3.31, td_loss=0.771, conservative_loss=2.54]

2025-04-12 16:48.05 [info     ] cql_SCIQ_CRG_20250412164636: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.0015895580768585204, 'time_algorithm_update': 0.0027519495487213137, 'loss': 3.312821018743515, 'td_loss': 0.7714872942894697, 'conservative_loss': 2.5413337247133256, 'time_step': 0.004460382246971131} step=20000
2025-04-12 16:48.05 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_20000.d3



Epoch 3/8: 100%|██████████| 10000/10000 [00:43<00:00, 229.49it/s, loss=3.3, td_loss=0.768, conservative_loss=2.53]

2025-04-12 16:48.48 [info     ] cql_SCIQ_CRG_20250412164636: epoch=3 step=30000 epoch=3 metrics={'time_sample_batch': 0.0015571813583374024, 'time_algorithm_update': 0.00265916690826416, 'loss': 3.2981040577173233, 'td_loss': 0.7679402119189501, 'conservative_loss': 2.530163845539093, 'time_step': 0.004333463597297669} step=30000
2025-04-12 16:48.48 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_30000.d3



Epoch 4/8: 100%|██████████| 10000/10000 [00:44<00:00, 223.98it/s, loss=3.28, td_loss=0.77, conservative_loss=2.51]

2025-04-12 16:49.33 [info     ] cql_SCIQ_CRG_20250412164636: epoch=4 step=40000 epoch=4 metrics={'time_sample_batch': 0.001584145402908325, 'time_algorithm_update': 0.0027355862140655517, 'loss': 3.2827232834339144, 'td_loss': 0.7703547284275294, 'conservative_loss': 2.5123685559511184, 'time_step': 0.004439278697967529} step=40000
2025-04-12 16:49.33 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_40000.d3



Epoch 5/8: 100%|██████████| 10000/10000 [00:41<00:00, 243.47it/s, loss=3.25, td_loss=0.767, conservative_loss=2.49]

2025-04-12 16:50.14 [info     ] cql_SCIQ_CRG_20250412164636: epoch=5 step=50000 epoch=5 metrics={'time_sample_batch': 0.0014845673561096192, 'time_algorithm_update': 0.002486291551589966, 'loss': 3.253868759727478, 'td_loss': 0.7671441103935241, 'conservative_loss': 2.4867246491670607, 'time_step': 0.004084591889381409} step=50000


2025-04-12 16:50.14 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_50000.d3


Epoch 6/8: 100%|██████████| 10000/10000 [00:40<00:00, 246.86it/s, loss=3.22, td_loss=0.763, conservative_loss=2.46]

2025-04-12 16:50.54 [info     ] cql_SCIQ_CRG_20250412164636: epoch=6 step=60000 epoch=6 metrics={'time_sample_batch': 0.0014580671310424804, 'time_algorithm_update': 0.002459042429924011, 'loss': 3.2205662796974184, 'td_loss': 0.7633792486727238, 'conservative_loss': 2.457187031292915, 'time_step': 0.0040291418552398685} step=60000


2025-04-12 16:50.54 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_60000.d3


Epoch 7/8: 100%|██████████| 10000/10000 [00:40<00:00, 246.11it/s, loss=3.19, td_loss=0.766, conservative_loss=2.43]


2025-04-12 16:51.35 [info     ] cql_SCIQ_CRG_20250412164636: epoch=7 step=70000 epoch=7 metrics={'time_sample_batch': 0.001463074779510498, 'time_algorithm_update': 0.0024663832426071166, 'loss': 3.19258749063015, 'td_loss': 0.7662884939938783, 'conservative_loss': 2.426298996782303, 'time_step': 0.0040413371562957765} step=70000
2025-04-12 16:51.35 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_70000.d3


Epoch 8/8: 100%|██████████| 10000/10000 [00:40<00:00, 246.20it/s, loss=3.15, td_loss=0.755, conservative_loss=2.39]

2025-04-12 16:52.16 [info     ] cql_SCIQ_CRG_20250412164636: epoch=8 step=80000 epoch=8 metrics={'time_sample_batch': 0.0014629671335220336, 'time_algorithm_update': 0.0024650146484375, 'loss': 3.1465596240997313, 'td_loss': 0.7550860061109066, 'conservative_loss': 2.3914736177921294, 'time_step': 0.004039595317840576} step=80000
2025-04-12 16:52.16 [info     ] Model parameters are saved to d3rlpy_logs/cql_SCIQ_CRG_20250412164636/model_80000.d3


In [5]:
for i in range(len(dataset.episodes)):
    print(dataset.episodes[i].rewards)

[[-0.051  ]
 [-0.01705]
 [ 9.93195]]
[[-0.01705]
 [ 9.98295]]
[[-0.235 ]
 [-1.645 ]
 [-0.0624]
 [-0.036 ]
 [-0.108 ]
 [ 7.9136]]
[[-0.02475]
 [ 9.97525]]
[[-0.033 ]
 [-0.0456]
 [-0.105 ]
 [-1.05  ]
 [-0.735 ]
 [ 8.0314]]
[[-0.01045]
 [ 9.98955]]
[[-0.081 ]
 [-0.0405]
 [-1.855 ]
 [ 8.0235]]
[[-0.02805]
 [ 9.97195]]
[[ -2.485 ]
 [ -3.55  ]
 [ -0.108 ]
 [ -0.1224]
 [ -0.242 ]
 [-16.5074]]
[[-0.03795]
 [ 9.96205]]
[[-0.02475]
 [-0.0561 ]
 [-0.072  ]
 [-0.0429 ]
 [-0.0429 ]
 [ 9.76135]]
[[-0.0165]
 [ 9.9835]]
[[-0.12525]
 [-0.2505 ]
 [-0.5745 ]
 [-5.81   ]
 [ 3.23975]]
[[-0.0902]
 [ 9.9098]]
[[-0.13 ]
 [-0.068]
 [-0.195]
 [-0.03 ]
 [-1.95 ]
 [ 7.627]]
[[-0.02035]
 [ 9.97965]]
[[-0.0143]
 [-0.0915]
 [-0.0377]
 [ 9.8565]]
[[-0.0143]
 [ 9.9857]]
[[-0.1005]
 [-0.0352]
 [-0.2245]
 [-0.0871]
 [ 9.5527]]
[[-0.0352]
 [ 9.9648]]
[[-0.0845 ]
 [-0.2175 ]
 [-0.0975 ]
 [-0.04875]
 [-0.0975 ]
 [ 9.45425]]
[[-0.0341]
 [ 9.9659]]
[[-0.018]
 [-0.036]
 [ 9.946]]
[[-0.01155]
 [ 9.98845]]
[[-0.24  ]
 [-0.0637]

In [6]:
-1.195 * 10**(-1)

-0.11950000000000001

In [7]:
len(dataset.episodes[0].observations[0])

593

In [29]:
cql = d3rlpy.algos.DiscreteCQLConfig(batch_size=128).create(device="cpu")
cql.fit(
    dataset,
    n_steps=150000,
    n_steps_per_epoch=10000,
    experiment_name='cql_overruling',
    # evaluators={"environment": d3rlpy.metrics.EnvironmentEvaluator(env)},
)



2025-04-12 16:08.58 [info     ] dataset info                   dataset_info=DatasetInfo(observation_signature=Signature(dtype=[dtype('float32')], shape=[(593,)]), action_signature=Signature(dtype=[dtype('int64')], shape=[(1,)]), reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)]), action_space=<ActionSpace.DISCRETE: 2>, action_size=13)
2025-04-12 16:08.58 [debug    ] Building models...            
2025-04-12 16:08.58 [debug    ] Models have been built.       
2025-04-12 16:08.58 [info     ] Directory is created at d3rlpy_logs/cql_overruling_20250412160858
2025-04-12 16:08.58 [info     ] Parameters                     params={'observation_shape': [593], 'action_size': 13, 'config': {'type': 'discrete_cql', 'params': {'batch_size': 128, 'gamma': 0.99, 'observation_scaler': {'type': 'none', 'params': {}}, 'action_scaler': {'type': 'none', 'params': {}}, 'reward_scaler': {'type': 'none', 'params': {}}, 'compile_graph': False, 'learning_rate': 6.25e-05, 'optim_factory': {'typ

Epoch 1/15: 100%|██████████| 10000/10000 [00:36<00:00, 276.87it/s, loss=0.0947, td_loss=0.0156, conservative_loss=0.0791]

2025-04-12 16:09.34 [info     ] cql_overruling_20250412160858: epoch=1 step=10000 epoch=1 metrics={'time_sample_batch': 0.0011970757484436035, 'time_algorithm_update': 0.002308729386329651, 'loss': 0.0946174117137678, 'td_loss': 0.01554801034766715, 'conservative_loss': 0.0790694012117936, 'time_step': 0.003595106887817383} step=10000
2025-04-12 16:09.34 [info     ] Model parameters are saved to d3rlpy_logs/cql_overruling_20250412160858/model_10000.d3



Epoch 2/15: 100%|██████████| 10000/10000 [00:36<00:00, 272.50it/s, loss=0.00253, td_loss=0.00241, conservative_loss=0.000115]

2025-04-12 16:10.11 [info     ] cql_overruling_20250412160858: epoch=2 step=20000 epoch=2 metrics={'time_sample_batch': 0.001210304617881775, 'time_algorithm_update': 0.002350711226463318, 'loss': 0.0025284769830526783, 'td_loss': 0.0024136788070318288, 'conservative_loss': 0.0001147981765858276, 'time_step': 0.0036523823499679565} step=20000
2025-04-12 16:10.11 [info     ] Model parameters are saved to d3rlpy_logs/cql_overruling_20250412160858/model_20000.d3



Epoch 3/15:  96%|█████████▋| 9630/10000 [00:36<00:01, 265.61it/s, loss=0.000576, td_loss=0.000562, conservative_loss=1.37e-5]


KeyboardInterrupt: 

In [9]:
len(dataset.episodes[i].observations[:1])

1

In [15]:

for i in range(30):
    print(cql.predict(dataset.episodes[i].observations[:4]))

[9 9 9]
[9 2]
[9 6 6 2]
[9 2]
[9 8 0 3]
[9 9]
[ 9  2  9 12]
[9 2]
[9 8 8 8]
[9 2]
[ 9  8 11  5]
[9 9]
[ 9  7 10  1]
[9 2]
[9 4 4 2]
[9 2]
[9 9 0 9]
[9 9]
[0 2 6 6]
[9 2]
[6 2 0 2]
[9 2]
[ 2  9 12]
[9 9]
[ 7  2 12]
[9 2]
[5 9]
[9 9]
[10  2  0  0]
[9 2]


In [79]:
# evaluate on test set
# input is an action, for each episode, specify the query first
test_data = pd.read_csv('../data/HEADLINES/embedded_HEADLINES_all_models_clean_test.csv')
len(test_data)

2000

In [80]:
test_data

query  \
0     Please determine the price direction (up, down...   
1     Please determine the price direction (up, down...   
2     Please determine the price direction (up, down...   
3     Please determine the price direction (up, down...   
4     Please determine the price direction (up, down...   
...                                                 ...   
1995  Please determine the price direction (up, down...   
1996  Please determine the price direction (up, down...   
1997  Please determine the price direction (up, down...   
1998  Please determine the price direction (up, down...   
1999  Please determine the price direction (up, down...   

                                              query_raw ref_answer  \
0     Q: Dec. gold gains $14.10, or 1.1%, to settle ...         up   
1     Q: gold slips as investors remain cautious fol...       down   
2      Q: spot gold quoted at $471.40 in asia trade\nA:       none   
3           Q: Gold prices inch up on weaker dollar\nA:         up   
4     Q: gold price seen averaging $1,770 in q4: gfm...    neutral   
...                                                 ...        ...   
1995  Q: gold futures log lowest settlement since ja...       down   
1996  Q: turkey's erdogan slams venezuela sanctions,...       none   
1997  Q: gold futures close 5.3% higher on day, up 1...         up   
1998  Q: Gold drops 4th day in a row as market weigh...       down   
1999  Q: Feb. gold at $1,166.80/oz in electronic tra...       none   

     gpt-4o-mini   gpt-4o llama-3-8B llama-3-70B mixtral-8x7B  \
0             up       up         up          up           up   
1           down     down       down        down         down   
2        neutral  neutral    neutral     neutral      neutral   
3             up       up         up          up           up   
4             up  neutral         up          up      neutral   
...          ...      ...        ...         ...          ...   
1995        down     down       down        down         down   
1996     neutral     none    neutral     neutral          NaN   
1997          up       up         up          up           up   
1998        down     down       down        down         down   
1999          up       up         up          up      neutral   

     gemini-1.5-flash-002 gemini-1.0-pro gemini-1.5-pro-002  \
0                      up             up                 up   
1                    down           down               down   
2                 neutral        neutral            neutral   
3                      up             up                 up   
4                 neutral        neutral            neutral   
...                   ...            ...                ...   
1995                 down           down               down   
1996                 none           none            neutral   
1997                   up             up                 up   
1998                 down           down               down   
1999                   up             up                 up   

     Phi-3.5-mini-instruct Phi-3-small-8k-instruct Phi-3-mini-4k-instruct  \
0                       up                      up                     up   
1                     down                    down                   down   
2                  neutral                    down                   none   
3                       up                      up                     up   
4                  neutral                    down                   none   
...                    ...                     ...                    ...   
1995                  down                    down                   down   
1996                  none                    down                   none   
1997                    up                      up                     up   
1998                  down                    down                   down   
1999               neutral                      up                     up   

     Phi-3-medium-4k-instruct  \
0   

In [92]:
def vectorize_history(history,ohe_actions, ohe_answers, max_iter=5,  method='ohe'):
    # history is a string of the form "model1: answer1; model2: answer2; ..."
    # we want to vectorize it into a numpy array 
    # we use the one hot encoding to vectorize the history
    if method == 'ohe':
        # split the history string into a list of model:answer pairs
        if history == '':
            return np.zeros((len(ohe_actions.categories_[0]) + len(ohe_answers.categories_[0]))*max_iter)  
        pairs = history.split('; ')
        # print(history)
        # create a dictionary to store the one hot encoded history
        history_dict = {}
        history_vec = []
        for pair in pairs:
            model, answer = pair.split(': ')
            history_dict[model] = answer
            action_vec = ohe_actions.transform(np.array([model]).reshape(1,-1)).toarray()
            answer_vec = ohe_answers.transform(np.array([answer]).reshape(1,-1)).toarray()
            # print('action_vec', action_vec[0], 'answer_vec', answer_vec[0])
            history_vec.extend(action_vec[0])
            history_vec.extend(answer_vec[0])
        # print('history_vec', history_vec, 'history_vec shape', len(history_vec))
        # fill up the remaining slots with zeros until max_iter
        history_vec = np.concatenate([history_vec, np.zeros(max_iter*(len(ohe_actions.categories_[0]) + len(ohe_answers.categories_[0])) - len(history_vec))])
    # print('history_vec shape', history_vec.shape)
    return history_vec

def train_vectorizer(dataset_name):
    df = load_dataset(dataset_name, 'train')
    # train a one hot encoder on answers and actions
    # we need to convert the answers and actions to a list of strings
    answers = df['ref_answer'].tolist()
    answers.append(np.nan)
    actions = ACTIONS_SPACE
    actions = np.array(actions).reshape(-1,1)
    answers = np.array(answers).reshape(-1,1)

    # train a one hot encoder on the answers and actions
    ohe_actions = OneHotEncoder()
    ohe_actions.fit(actions)
    ohe_answers = OneHotEncoder()
    ohe_answers.fit(answers)
    return ohe_actions, ohe_answers



In [ ]:
def evaluate(row, max_budget, max_iter=5, ohe_actions=None, ohe_answers=None):
    # given an action, it will return the reward, observation, if terminated 
    observations = []
    actions = []
    rewards = []
    terminals = []
    
    query = row['query_raw']
    ref_answer = row['ref_answer']
    
    # Initial state: query embedding + empty history + remaining budget
    history = {}
    remaining_budget = max_budget
    
    # Get query embedding by using the embedding column in the dataframe
    query_embedding = row['embedding']
    
    # Create initial observation (query embedding + history + remaining budget)
    # For history, we'll flatten it into a string representation
    history_str = ""
    current_obs = np.concatenate([
        query_embedding, # shape: (512,)
        vectorize_history(history_str, ohe_actions, ohe_answers, method='ohe' ),
        np.array([remaining_budget])
    ])

    
